name: language_learning_ui
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^11.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^2.2.4
  google_fonts: ^8.0.2
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/azerbaijan.png
    - assets/images/course-1.png
    - assets/images/course-2.png
    - assets/images/course-3.png
    - assets/images/course-4.png
    - assets/images/course-5.png
    - assets/images/england.png
    - assets/images/home.png
    - assets/images/korea.png
    - assets/images/lesson.png
    - assets/images/person-1.png
    - assets/images/person-2.png
    - assets/images/person-3.png
    - assets/images/profile.png
    - assets/images/russia.png
    - assets/images/turkey.png
    - assets/svg/